matrix:
  include:
    - language: python
      python: "3.4"
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - python3-setuptools
      install: sudo easy_install3 regex brotli
    - language: python
      python: "3.6"
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - python3-setuptools
      install: sudo easy_install3 regex brotli
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      install: sudo -H pip3 install regex brotli
script: python test.py
