matrix:
  include:
    - language: python
      python: "3.4"
    - language: python
      python: "3.6"
    - language: python
      python: "3.7"
      dist: xenial
      sudo: true
script: python test.py
