matrix:
  include:
    - language: python
      python: "3.4"
    - language: python
      python: "3.6"
    - language: generic
      os: osx
      before_install:
        - brew upgrade python
        - virtualenv env -p python3
        - source env/bin/activate
      install: sudo -H pip3 install -r requirements.txt
script: python test.py
