environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python36-x64"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pip install regex brotli"
  - "%PYTHON%\\python.exe test.py"
